/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackListTop: typeof import('./src/components/AppBackListTop.vue')['default']
    AppCountdownButton: typeof import('./src/components/AppCountdownButton.vue')['default']
    AppDescriptions: typeof import('./src/components/AppDescriptions.vue')['default']
    AppDescriptionsItem: typeof import('./src/components/AppDescriptionsItem.vue')['default']
    AppIconContainer: typeof import('./src/components/AppIconContainer.vue')['default']
    AppPictureUpload: typeof import('./src/components/AppPictureUpload.vue')['default']
    AppRadioButtonGroup: typeof import('./src/components/AppRadioButtonGroup.vue')['default']
    AppSegmented: typeof import('./src/components/AppSegmented.vue')['default']
    AppSvgIcon: typeof import('./src/components/AppSvgIcon.vue')['default']
    CaptchaWrapper: typeof import('./src/components/captcha/CaptchaWrapper.vue')['default']
    ClickCaptcha: typeof import('./src/components/captcha/ClickCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideCaptcha: typeof import('./src/components/captcha/SlideCaptcha.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCalendar: typeof import('tdesign-mobile-vue')['Calendar']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup']
    TDialog: typeof import('tdesign-mobile-vue')['Dialog']
    TEmpty: typeof import('tdesign-mobile-vue')['Empty']
    TFooter: typeof import('tdesign-mobile-vue')['Footer']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TImageViewer: typeof import('tdesign-mobile-vue')['ImageViewer']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLink: typeof import('tdesign-mobile-vue')['Link']
    TList: typeof import('tdesign-mobile-vue')['List']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TResult: typeof import('tdesign-mobile-vue')['Result']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
  }
}
